### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by DooMGuy87** [h4mu/rott94#10]
I'm using the latest android build (tested the 3 apks from the releases page) and the game runs fine, but the background music doesn't play. My device has Android Pie.
Is there a way to make it work?

**Comment by h4mu** [comment]
Hi,

I don't have background music either but I haven't noticed it before. I think the music files get placed in the wrong folder. I will investigate.

**Comment by h4mu** [comment]
Could be related to https://bugzilla.libsdl.org/show_bug.cgi?id=4754

**Comment by DooMGuy87** [comment]
First of all, sorry for the super late reply.
I see...  so, does this means that it isn't fixable then?

**Comment by h4mu** [comment]
Turns out that linked issue was a red herring. SDL_mixer simply doesn't have native support for MIDI on Android. I think it might be possible to make it work with Timidity but then you need to copy some sound fonts next to your app which takes up space so instead I added code that uses the built-in Android functionality for MIDI play. Try the latest release to see if it works for you: https://github.com/h4mu/rott94/releases/tag/v0.87-beta

**Comment by DooMGuy87** [comment]
I've just tried v0.87-beta , but it doesn't work. When I open it, I get a black screen, the Apogee fanfare starts to play and the app closes. Well the music works now at least... :P
Tried with the 3 debug apps (I can't install the unsigned ones)

**Comment by h4mu** [comment]
Yes sorry I originally tested it on my KitKat tablet where it worked but there was a small mistake in the JNI code which caused it to fail on Android 9. Should be fixed now, please try again.

Only the debug APKs work without signature, I might start producing signed release packages at some point soon.

**Comment by DooMGuy87** [comment]
Sorry for the late reply (again...).
Now the music works, thank you very much!
I'm still having some problems with the control layout, it's a bit difficult to get used, but that's another subject....
Thanks again for your work! :D
Thanks f
